# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [7]:
# memory size for an element
print(arr.itemsize)
# memory size for an array
print(arr.itemsize*len(arr))

8
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [111]:
#to be run in the command prompt or anaconda prompt.
python -c "import numpy as np; np.info(np.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr = np.zeros(10)
arr[4]=1
print(arr)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [21]:
#vec = []
#i = 10
#while i < 50:
#    vec.append(i)
#    i+=1
#print(vec)

vec = []
vec = np.arange(10,50)
print(vec)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [22]:
#rev = []
#i = len(vec)
#while i > 0:
#    rev.append(vec[i-1])
#    i-=1
#print(rev)
#or
vec = vec[::-1]
print(vec)

[49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [26]:
int =[]
for i in range(9):
    int.append(i)
int = np.resize(int,(3,3))
print(int)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [28]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [29]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [33]:
ran =[]
for i in range(27):
    ran.append(np.random.random())
ran = np.resize(ran,(3,3,3))
print(ran)

[[[9.74540071e-01 1.43751088e-01 4.01764124e-01]
  [7.90866389e-02 7.30579958e-01 9.24326327e-02]
  [5.13895027e-01 7.53787021e-02 2.11972235e-01]]

 [[1.42332330e-01 5.24428456e-01 8.74640068e-01]
  [5.39533241e-01 6.72432139e-01 8.11688130e-01]
  [2.40561145e-05 3.09899410e-01 5.33463128e-02]]

 [[6.54338952e-01 3.07141946e-01 3.97482914e-01]
  [8.34597413e-01 2.76100274e-01 2.74674968e-01]
  [1.65941387e-01 7.86979888e-01 4.09710020e-01]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [35]:
rand = np.random.random((10,10))
print(rand)
print("Max value:", rand.max())
print("Min value",rand.min())

[[7.71604780e-01 5.98923787e-01 9.88692654e-02 1.21165373e-01
  1.71263394e-02 3.61097445e-01 5.95855321e-01 7.26070056e-01
  1.91144242e-01 8.18932462e-01]
 [4.83197990e-01 9.16319568e-01 7.72708953e-01 4.53165460e-01
  3.40971115e-01 5.11958463e-01 8.35795967e-01 8.20545775e-02
  2.26028595e-01 1.73976979e-01]
 [1.28307979e-02 6.77914090e-01 2.35679267e-01 3.24017554e-01
  6.75376109e-01 7.31650009e-01 8.79489342e-01 2.23215469e-01
  7.59594365e-01 5.47783424e-01]
 [7.26523945e-04 2.21723790e-01 6.13907915e-01 7.51143801e-01
  9.00195626e-01 9.43854688e-01 3.25851203e-01 8.05295964e-01
  2.04131039e-01 8.63460390e-01]
 [7.33655047e-01 8.65662641e-01 7.65417076e-01 9.77231229e-01
  4.97685571e-01 5.05010452e-01 2.43898370e-01 4.42291511e-01
  1.98907327e-01 1.94189174e-01]
 [9.94888747e-02 3.32874361e-01 9.62243650e-01 8.97978699e-01
  1.04937694e-01 1.02496035e-01 5.08810314e-01 1.68694324e-01
  8.26389469e-02 2.79047857e-01]
 [4.75797385e-01 1.05766935e-01 8.10300456e-01 2.21418395e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [39]:
vec = np.random.random(30)
print(vec)
print("Mean value: ",vec.mean())

[0.52432582 0.72388602 0.92408574 0.76452437 0.2176667  0.51648205
 0.7949383  0.14801154 0.09625413 0.65928183 0.01891168 0.45064402
 0.42295828 0.11498213 0.10486376 0.02005176 0.87942476 0.93373375
 0.29642237 0.98424791 0.04833976 0.75221788 0.2316846  0.98769454
 0.50210469 0.77994372 0.23964758 0.95822937 0.07573856 0.11813548]
Mean value:  0.476314435972224


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [43]:
twod = np.zeros((5,5))
twod[0,:]=1
twod[4,:]=1
twod[:,0]=1
twod[:,4]=1
print(twod)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
two = np.ones((5,5))
twod[0,:]=0
twod[4,:]=0
twod[:,0]=0
twod[:,4]=0
print(twod)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [3]:
import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
#nan (not a number)
#False (part of definition)
#False 
#nan (Even that isnt a number)
#true (nan is present in the set)
#False (because of round-off erorr)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [14]:
val = np.matrix([[1,2,3,4]])
d = np.diag(val[0].A1,k=-1)
print(d)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [38]:
check = np.zeros(64)
for i in range(8):
    if i%2==0:
        check[8*i:8*(i+1):2] = 1
    else:
        check[(8*i)+1:8*(i+1)+1:2] = 1
check.resize(8,8)
print(check)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [5]:

print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [10]:
tilepat = np.tile(np.array([[1,0],[0,1]]),(4,4))
print(tilepat)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [17]:
rand = np.random.randint(100,size=(25)).reshape(5,5)
print(rand)
rand = (rand - np.mean(rand))/np.std(rand)
print(rand)

[[14 14 69 31  9]
 [66  4 49 62 50]
 [34 62 49 24 19]
 [19 21 79 40 42]
 [90  0 92 20 50]]
[[-1.01692687 -1.01692687  1.10488565 -0.36109391 -1.20981892]
 [ 0.98915042 -1.40271097  0.33331746  0.83483678  0.37189587]
 [-0.24535868  0.83483678  0.33331746 -0.63114278 -0.82403483]
 [-0.82403483 -0.74687801  1.49066974 -0.01388823  0.06326859]
 [ 1.91503225 -1.55702461  1.99218907 -0.78545642  0.37189587]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [22]:
col = np.dtype([('r',np.ubyte),('b',np.ubyte),('g',np.ubyte),('a',np.ubyte)])

[('r', 'u1'), ('b', 'u1'), ('g', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
mult = np.dot(np.random.random((5,3)),np.random.random((3,2)))
print(mult)

[[0.59733045 0.76530988]
 [0.69805128 0.97082961]
 [1.03475809 0.67964359]
 [1.02025698 1.08828498]
 [0.99565451 0.66562171]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [32]:
ar = np.arange(20)
for z in ar:
    if z>3 and z<8:
        ar[z]=-1*ar[z]
print(ar)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [34]:
#9
#10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [54]:
#Z**Z
#Z <- Z
#1j*Z
#Z/1/1
#Z<Z>Z

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [166]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [66]:
round = np.random.uniform(-5,5,10)
print(round)
print (np.copysign(np.ceil(np.abs(round)), round))

[ 4.83804378  4.70203271  2.97403376 -1.6809197   4.90565678  0.70998278
  2.75099499  3.37376652  3.14116214 -4.26799078]
[ 5.  5.  3. -2.  5.  1.  3.  4.  4. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [64]:
A = np.random.randint(10,size=(8))
B = np.random.randint(10,size=(8))
print(np.intersect1d(A,B))

[0 5 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [69]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

[inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [72]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2021-09-07
2021-09-08
2021-09-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [74]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [81]:
A = np.random.randint(3,size=(3))
B = np.random.randint(3,size=(3))
np.add(A,B,out=B)
np.divide(A,2,out=A,casting = 'unsafe')
np.negative(A,out=A)
np.multiply(A,B,out=A)

[ 0  0 -3]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [83]:
Ar = np.random.uniform(0,10,10)

print (np.floor(Ar))
print (np.ceil(Ar)-1)
print (Ar - Ar%1)
print (np.trunc(Ar))

[3. 8. 9. 9. 9. 6. 4. 5. 3. 2.]
[3. 8. 9. 9. 9. 6. 4. 5. 3. 2.]
[3. 8. 9. 9. 9. 6. 4. 5. 3. 2.]
[3. 8. 9. 9. 9. 6. 4. 5. 3. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [86]:
Ar = np.random.uniform(0,4,(5,5))
print(Ar)

[[1.15929618 3.7020349  1.01747964 1.06174758 2.95197639]
 [3.08447131 2.82991697 1.87444719 2.56093967 1.70590278]
 [1.9843484  2.90270848 0.61293939 1.47270098 0.49492748]
 [1.465302   3.48040239 3.23356031 2.00157957 3.22123215]
 [1.88978135 0.24319509 1.48325704 1.53766078 1.62423868]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [90]:

def genf():
    for i in range(10):
        yield i
Ar = np.fromiter(genf(),dtype=float,count=-1)
print(Ar)
        

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [96]:
A = np.arange(0,1,0.095)[1:]
print(A)

[0.095 0.19  0.285 0.38  0.475 0.57  0.665 0.76  0.855 0.95 ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [97]:
ran = np.random.random(10)
ran.sort()
print(ran)

[0.2435762  0.33631803 0.41606852 0.47469381 0.47811266 0.51430424
 0.63940703 0.76146341 0.9067659  0.98932207]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [99]:
Ar = np.arange(10)
print(np.add.reduce(Ar))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [106]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(np.array_equal(A,B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [108]:
ar = np.ones(10)
ar.flags.writeable = False
#ar[5] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [109]:
cord = np.random.random((10,2))
X,Y = cord[:,0], cord[:,1]
R = np.sqrt(pow(X,2)+pow(Y,2))
T = np.arctan2(Y,X)
print(R)
print(T)

[0.76634147 0.18765663 0.76715078 1.09809123 0.85091779 1.10552616
 1.14634004 0.81486758 0.63391537 0.88618234]
[0.94972986 0.25307991 0.29750914 0.63085101 0.91148287 0.91892803
 1.01989116 0.28532388 1.29569773 1.36247922]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [117]:
max = np.random.randint(0,10,5)
print(max)
s = np.argmax(max)
max[s]=0
print(max)

[1 9 5 2 3]
[1 0 5 2 3]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [137]:
area = np.zeros((11,11),[('x',float),('y',float)])
k=0
l=0
for i in range(11):
    l=0
    for j in range(11):
        area[i,j]=(k,l)
        l+=0.1
    k+=0.1
print(area)       
                
                

[[(0. , 0. ) (0. , 0.1) (0. , 0.2) (0. , 0.3) (0. , 0.4) (0. , 0.5)
  (0. , 0.6) (0. , 0.7) (0. , 0.8) (0. , 0.9) (0. , 1. )]
 [(0.1, 0. ) (0.1, 0.1) (0.1, 0.2) (0.1, 0.3) (0.1, 0.4) (0.1, 0.5)
  (0.1, 0.6) (0.1, 0.7) (0.1, 0.8) (0.1, 0.9) (0.1, 1. )]
 [(0.2, 0. ) (0.2, 0.1) (0.2, 0.2) (0.2, 0.3) (0.2, 0.4) (0.2, 0.5)
  (0.2, 0.6) (0.2, 0.7) (0.2, 0.8) (0.2, 0.9) (0.2, 1. )]
 [(0.3, 0. ) (0.3, 0.1) (0.3, 0.2) (0.3, 0.3) (0.3, 0.4) (0.3, 0.5)
  (0.3, 0.6) (0.3, 0.7) (0.3, 0.8) (0.3, 0.9) (0.3, 1. )]
 [(0.4, 0. ) (0.4, 0.1) (0.4, 0.2) (0.4, 0.3) (0.4, 0.4) (0.4, 0.5)
  (0.4, 0.6) (0.4, 0.7) (0.4, 0.8) (0.4, 0.9) (0.4, 1. )]
 [(0.5, 0. ) (0.5, 0.1) (0.5, 0.2) (0.5, 0.3) (0.5, 0.4) (0.5, 0.5)
  (0.5, 0.6) (0.5, 0.7) (0.5, 0.8) (0.5, 0.9) (0.5, 1. )]
 [(0.6, 0. ) (0.6, 0.1) (0.6, 0.2) (0.6, 0.3) (0.6, 0.4) (0.6, 0.5)
  (0.6, 0.6) (0.6, 0.7) (0.6, 0.8) (0.6, 0.9) (0.6, 1. )]
 [(0.7, 0. ) (0.7, 0.1) (0.7, 0.2) (0.7, 0.3) (0.7, 0.4) (0.7, 0.5)
  (0.7, 0.6) (0.7, 0.7) (0.7, 0.8) (0.7, 0.9) (0.7

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [150]:
X = np.arange(6)
Y = X + 0.5
cauchy = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(cauchy))

396.03682955582303


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [151]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [159]:
np.set_printoptions(threshold=256)
Z = np.arange(256).reshape(16,16)
print(Z)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31]
 [ 32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63]
 [ 64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175]
 [176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191]
 [192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207]
 [208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223]
 [224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [160]:
ar = np.arange(50)
v = np.random.uniform(0,50)
print(v)
index = (np.abs(Z-v)).argmin()
print(ar[index])

22.63978414179832
23


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [164]:
Z = np.zeros(5, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [165]:
dist = np.random.random((10,2))
X,Y = np.atleast_2d(dist[:,0], dist[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.86509721 0.32558533 0.8389058  0.64328875 0.29602506
  0.39963727 0.43191884 0.73478345 0.53711018]
 [0.86509721 0.         0.89203163 0.47374396 0.67720412 0.70183916
  0.62201783 0.48266494 0.19878252 0.81818477]
 [0.32558533 0.89203163 0.         1.02540104 0.90280006 0.56780057
  0.27423741 0.6008091  0.82834344 0.83641379]
 [0.8389058  0.47374396 1.02540104 0.         0.30717716 0.55958847
  0.81914811 0.42655815 0.31000397 0.49931837]
 [0.64328875 0.67720412 0.90280006 0.30717716 0.         0.34796524
  0.76832518 0.35031576 0.47895744 0.19435382]
 [0.29602506 0.70183916 0.56780057 0.55958847 0.34796524 0.
  0.49304626 0.21920509 0.52962662 0.27408137]
 [0.39963727 0.62201783 0.27423741 0.81914811 0.76832518 0.49304626
  0.         0.4238249  0.58061623 0.76115862]
 [0.43191884 0.48266494 0.6008091  0.42655815 0.35031576 0.21920509
  0.4238249  0.         0.3162071  0.39566863]
 [0.73478345 0.19878252 0.82834344 0.31000397 0.47895744 0.52962662
  0.58061623 0.31620

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [168]:
Z = np.ones(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[1 1 1 1 1 1 1 1 1 1]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [12]:
from io import StringIO

chars = StringIO('''1, 2, 3, 4, 5

                    6,  ,  , 7, 8

                     ,  , 9, 10, 11
''')
read = np.genfromtxt(chars, delimiter=",", dtype=np.int32,filling_values=0)
print(read)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [15]:
Enu = np.arange(16).reshape(4,4)
for index, value in np.ndenumerate(Enu):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [22]:
X, Y = np.meshgrid(np.linspace(-1,1,6), np.linspace(-1,1,6))

D = np.sqrt(pow(X,2)+pow(Y,2))
sigma, mu = 1.0, 0.0
G = np.exp(-( pow((D-mu),2) / ( 2.0 * pow(sigma,2) ) ) )
print(G)

[[0.36787944 0.50661699 0.59452055 0.59452055 0.50661699 0.36787944]
 [0.50661699 0.69767633 0.81873075 0.81873075 0.69767633 0.50661699]
 [0.59452055 0.81873075 0.96078944 0.96078944 0.81873075 0.59452055]
 [0.59452055 0.81873075 0.96078944 0.96078944 0.81873075 0.59452055]
 [0.50661699 0.69767633 0.81873075 0.81873075 0.69767633 0.50661699]
 [0.36787944 0.50661699 0.59452055 0.59452055 0.50661699 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [24]:
p = 10
ran = np.zeros((8,8))
np.put(ran, np.random.choice(range(8*8), p, replace = False),1)
print(ran)

[[1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [31]:
X = np.random.rand(5, 10)
print(X - X.mean(axis=1, keepdims=True))

[[ 0.03332481  0.40493364  0.14596974  0.0015885  -0.25904657 -0.18732868
  -0.21478023  0.37900822 -0.14446801 -0.15920143]
 [ 0.06367542  0.08385375 -0.24969118  0.44536864 -0.31250923  0.22792161
  -0.18179527  0.07885554 -0.28634677  0.1306675 ]
 [ 0.08512733 -0.17417207 -0.2494472  -0.14037453  0.22523909 -0.22951484
  -0.22296052  0.54327873  0.33059046 -0.16776647]
 [-0.60552602 -0.37456485  0.22071952  0.25432144 -0.04731179  0.1974345
   0.07063713  0.17669307  0.26600165 -0.15840464]
 [-0.05998217  0.23798162  0.04562541  0.2751154  -0.06552924  0.37568535
  -0.19941203 -0.28732701 -0.32705163  0.0048943 ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [35]:
ar = np.random.rand(3,3)
print(ar)

print(ar[ar[:,1].argsort()])

[[0.71920963 0.4293519  0.49104542]
 [0.00111686 0.20874764 0.16364811]
 [0.96598276 0.66877    0.72069093]]
[[0.00111686 0.20874764 0.16364811]
 [0.71920963 0.4293519  0.49104542]
 [0.96598276 0.66877    0.72069093]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [46]:
nul = np.random.randint(-1,2,(2,7))
print(nul)
print((~nul.any(axis=0)).any())

[[ 1 -1  1 -1  1  1  1]
 [-1  0  1  1  0  1 -1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [49]:
Z = np.random.uniform(0,10,10)
val = 0.5
m = Z.flat[np.abs(Z - val).argmin()]
print(m)

0.6335410088828142


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [53]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,res in it: 
    res[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [56]:
class Array(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = Array(np.arange(8), "name_given")
print (Z.name)

name_given


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [64]:
fir = np.ones(10)
print(fir)
sec = np.random.randint(0,len(fir),20)
print(sec)
np.add.at(fir, sec, 1)
print(fir)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3 9 3 3 9 8 0 6 1 5 8 2 7 7 0 8 6 9 9 4]
[3. 2. 2. 4. 2. 2. 3. 3. 4. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = np.random.rand(5)
Y = np.random.rand(5)
F = np.bincount(I,X)
print(F)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [70]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)

colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [71]:
mat = np.random.randint(0,20,(3,3,3,3))
sum = mat.sum(axis=(-2,-1))
print(sum)

[[ 82  85  76]
 [102 101  84]
 [ 65  70  82]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [75]:
ar1 = np.random.uniform(0,1,100)
ar2 = np.random.randint(0,10,100)
import pandas as pd
print(pd.Series(ar1).groupby(ar2).mean())

0    0.552530
1    0.621465
2    0.511970
3    0.427170
4    0.438862
5    0.634837
6    0.579033
7    0.542457
8    0.506686
9    0.515809
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [77]:
one = np.random.randint(0,10,(5,5))
two = np.random.randint(0,10,(5,5))

print(np.diag(np.dot(one, two)))

[183  95  61 120 113]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [78]:
Z = np.array([1,2,3,4,5])
len(Z) = n
Z1 = np.zeros(n + (n-1)*3)
Z1[::4] = Z
print(Z1)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [80]:
arA = 3*np.ones((5,5,3))
arB = 2*np.ones((5,5))
print(arA * arB[:,:,None])

[[[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]]


#### 72. How to swap two rows of an array? (★★★)

In [83]:
sp = np.arange(25).reshape(5,5)
sp[[2,1]] = sp[[1,2]]
print(sp)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [92]:
faces = np.random.randint(0,100,(10,3))

F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
print(F)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[[35 91]
 [91 38]
 [38 35]
 [34 96]
 [96 60]
 [60 34]
 [66 38]
 [38 39]
 [39 66]
 [83 88]
 [88 93]
 [93 83]
 [93 30]
 [30 38]
 [38 93]
 [81 84]
 [84 20]
 [20 81]
 [94 96]
 [96 11]
 [11 94]
 [65 73]
 [73 59]
 [59 65]
 [ 0 65]
 [65 75]
 [75  0]
 [30 97]
 [97 51]
 [51 30]]
[( 0, 65) ( 0, 75) (11, 94) (11, 96) (20, 81) (20, 84) (30, 38) (30, 51)
 (30, 93) (30, 97) (34, 60) (34, 96) (35, 38) (35, 91) (38, 39) (38, 66)
 (38, 91) (38, 93) (39, 66) (51, 97) (59, 65) (59, 73) (60, 96) (65, 73)
 (65, 75) (81, 84) (83, 88) (83, 93) (88, 93) (94, 96)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [93]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [100]:
def average(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    print(ret[n-1:])
    return ret[n - 1:] / n
av = np.arange(20)
print(average(av,3))

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48. 51. 54.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [105]:
from numpy.lib import stride_tricks

def shift(a):
    shape = (a.size - 4, 3)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
res = shift(np.arange(10))
print(res)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


##### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [107]:
one = np.random.uniform(-1.0,1.0,20)
print(np.negative(one, out=one))

[-0.73717575 -0.09453103 -0.57453099 -0.89453302  0.97984264  0.32585134
  0.05202209  0.04204232  0.50478519  0.16807491 -0.7688184  -0.63683323
  0.82911401  0.14016614 -0.37323191 -0.10147132  0.4021466   0.85625907
 -0.78927116 -0.28564706]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [60]:
def distance(P0, P1, p):
    len1 = P1 - P0
    L = (len1**2).sum(axis=1)
    M = -((P0[:,0]-p[...,0])*len1[:,0] + (P0[:,1]-p[...,1])*len1[:,1]) / L
    M = M.reshape(len(M),1)
    N = P0 + M*len1 - p
    return np.sqrt((N**2).sum(axis=1))

a = np.random.uniform(-10,10,(10,2))
b = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(a, b, p))

[ 0.33752177 15.73621408  7.33478135 11.89093015  4.88580363  0.19048876
  4.07798538  4.04155154  4.3887883   2.37953079]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [63]:
P0 = np.random.uniform(-1, 1, (10,2))
P1 = np.random.uniform(-1, 1, (10,2))
p = np.random.uniform(-1, 1, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[0.11840855 0.48951413 0.32155302 0.76990296 0.16254098 0.35627979
  0.48631737 0.0560819  0.85408518 0.93524521]
 [0.11181545 0.17122618 0.61433043 0.35702287 0.83129786 1.19588594
  0.3780804  0.1158653  0.29509234 0.25428445]
 [0.5852637  0.51363717 1.06524476 0.09466275 1.23749821 0.68339175
  0.12008423 0.58692945 0.52091931 0.11642567]
 [0.16129279 0.29981228 0.42298307 0.22284325 0.63678057 1.13379788
  0.31063858 0.17458562 0.09931085 0.09603259]
 [0.04257259 0.66549798 0.57278905 0.93524178 0.41696163 0.28709918
  0.56255948 0.031589   1.10673135 1.13345997]
 [0.9945965  0.70421172 0.90846879 0.46365147 1.03768285 0.121952
  0.68458267 0.97623848 0.17797146 0.40908684]
 [0.6772683  0.59996763 1.11666637 0.05227442 1.28269603 0.61074895
  0.19105597 0.6792396  0.54159596 0.08969598]
 [0.66460918 0.93929796 0.19146787 0.13526033 0.04311422 1.32533028
  0.48396248 0.69805015 0.38962124 0.10906527]
 [0.85031098 1.0681782  0.20486495 0.30749845 0.04587788 1.52780916
  0.68552865 0

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [84]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R  = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

Rstart = np.zeros((len(shape),)).astype(int)
Rstop  = np.array(list(shape)).astype(int)
Zstart = (P-Rs//2)
Zstop  = (P+Rs//2)+Rs%2

Rstart = (Rstart - np.minimum(Zstart,0)).tolist()
Zstart = (np.maximum(Zstart,0)).tolist()
Rstop = np.maximum(Rstart, (Rstop - np.maximum(Zstop-Zs,0))).tolist()
Zstop = (np.minimum(Zstop,Zs)).tolist()

R[[slice(start,stop) for start,stop in zip(Rstart,Rstop)]] = Z[[slice(start,stop) for start,stop in zip(Zstart,Zstop)]]
print(Z)
print(R)


defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

[[2 3 8 4 2 4 7 3 2 3]
 [3 9 8 3 6 1 9 7 4 7]
 [7 7 1 7 9 5 6 1 4 5]
 [6 6 3 2 9 6 6 6 0 4]
 [1 2 3 1 2 8 0 4 3 7]
 [7 3 5 4 5 7 6 4 3 5]
 [1 9 0 5 3 8 5 8 3 9]
 [9 5 0 6 5 8 3 2 5 9]
 [4 1 5 7 7 4 8 2 3 0]
 [3 6 5 2 8 2 3 2 2 0]]
[[0 0 0 0 0]
 [0 2 3 8 4]
 [0 3 9 8 3]
 [0 7 7 1 7]
 [0 6 6 3 2]]


<ipython-input-84-0f8b805e65b0>:21: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[[slice(start,stop) for start,stop in zip(Rstart,Rstop)]] = Z[[slice(start,stop) for start,stop in zip(Zstart,Zstop)]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [73]:
z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
type(z[1])
x=np.arange(z[1],z[1+4])
print(x)
y=[]
for i in range(14):
           k=np.arange(z[i],z[i]+4)
           y.append(k)
print(np.array(y))

[2 3 4 5]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]]


#### 82. Compute a matrix rank (★★★)

In [72]:
x = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.linalg.matrix_rank(x))

2


#### 83. How to find the most frequent value in an array?

In [70]:
x = np.random.randint(0,15,100)
print(x)
freq_value=np.bincount(x).argmax()
print(freq_value)

[ 3 12  2 13  3 10  8  1 14  9  3 10  9 13 13  4  0  6  7 10  5 12  2  1
  2 14  8  7  9  2  7 10  5  4 14  7 11  2  1  0  8  6  1 10  7  0 13 10
  7  4  6  8  9 10  9  6 10  8  4  7  4  7 11  4  6  8 11  0  1  8  9 11
  9  3  8  5  2  6 11  2 10 13 14  1 13  4  2  9  9  5 12 11  2  9 12 11
  4 13 14 14]
9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [71]:
x= np.random.uniform(0,10,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
blocks = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(blocks)

[[[[0 1 0]
   [1 0 1]
   [0 1 0]]]


 [[[1 0 1]
   [0 1 0]
   [0 1 0]]]


 [[[0 1 0]
   [0 1 0]
   [1 0 0]]]


 [[[0 1 0]
   [1 0 0]
   [0 0 0]]]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [69]:
class Symetric2D(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric2D, self).__setitem__((i,j), value)
        super(Symetric2D, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric2D)

Sym_array = symetric(np.random.randint(0,10,(5,5)))
print(Sym_array)

[[ 0 10 12  6 14]
 [10  0  6 10 10]
 [12  6  1  7  6]
 [ 6 10  7  6 11]
 [14 10  6 11  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [67]:
p, n = 10, 20
A = np.ones((p,n,n))
print(A)
V = np.ones((p,n,1))
print(V)
S = np.tensordot(A, V, axes=[[0, 2], [0, 1]])
print(S)

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[[1.]
  [

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [66]:
x = np.ones((16,16))
k = 4
Sum = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),
                                       np.arange(0, x.shape[1], k), axis=1)
print(Sum)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [94]:
import sys
np.set_printoptions(threshold=sys.maxsize)
def itera(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])


    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = itera(Z)
print(Z,'\n')

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  1 1 0 0 0 0 0 0 1 0 1 1 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  1 1 1 0 0 0 0 1 1 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 0 1
  0 0 1 1 1 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0

#### 89. How to get the n largest values of an array (★★★)

In [65]:
x = np.random.randint(0,600,1000)
n = 10
print (x[np.argsort(x)[-n:]])

[594 594 594 594 594 595 595 595 597 598]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [87]:
def cart(arrays):
    arrays = [np.array(a) for a in arrays]
    shape = (len(x) for x in arrays)
    #print(x)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cart(([1, 2, 3], [4, 5], [6, 7])))

[2 3 4 5]
[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [2]:
 num=np.array([1,2,3,4])
col=np.array(['Red','Green','White','Orange'])
result= np.core.records.fromarrays([num, col],names='a,b')
print(result)

[(1, 'Red') (2, 'Green') (3, 'White') (4, 'Orange')]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [23]:
x = np.random.rand(5000)

print(np.power(x,3))
print(x*x*x)
print(pow(x,3))

[0.04102589 0.51086298 0.0355046  ... 0.22924922 0.66527815 0.45027607]
[0.04102589 0.51086298 0.0355046  ... 0.22924922 0.66527815 0.45027607]
[0.04102589 0.51086298 0.0355046  ... 0.22924922 0.66527815 0.45027607]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [19]:
A = np.random.randint(0,8,(8,3))
B = np.random.randint(0,8,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
res = np.where(C.any((3,1)).all(1))
print(res)

(array([1, 5, 7], dtype=int64),)


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [22]:
Z = np.random.randint(0,5,(10,3))

res = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(res)

res [[2 3 1]
 [4 2 1]
 [1 4 3]
 [2 4 4]
 [4 0 1]
 [3 3 4]
 [3 3 1]
 [1 0 1]
 [4 3 4]
 [2 0 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [43]:
I = np.random.randint(0,16,(1,10))
print(I)
K = I.reshape(-1,1)
J = 2**np.arange(8)
L = (K & J != 0).astype(int)
print(L[:,::-1])

[[ 3  6 13  9  3  4 12 10 10  8]]
[[0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 1 1 0 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 1 0 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 1 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [40]:
Z = np.random.randint(0,2,(6,3))
uniq = np.unique(Z, axis=0)
print(uniq)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [45]:
A = [1,2,3,4,5,6,7,8,9]
B = [9,8,7,6,5,4,3,2,1]
print("sum",np.einsum('i->', A))
print("multiply",np.einsum('i,i->i', A, B))
print("inner prod",np.einsum('i,i', A, B))
print("outer prod",np.einsum('i,j->ij', A, B))

sum 45
multiply [ 9 16 21 24 25 24 21 16  9]
inner prod 165
outer prod [[ 9  8  7  6  5  4  3  2  1]
 [18 16 14 12 10  8  6  4  2]
 [27 24 21 18 15 12  9  6  3]
 [36 32 28 24 20 16 12  8  4]
 [45 40 35 30 25 20 15 10  5]
 [54 48 42 36 30 24 18 12  6]
 [63 56 49 42 35 28 21 14  7]
 [72 64 56 48 40 32 24 16  8]
 [81 72 63 54 45 36 27 18  9]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [47]:

theta = np.arange(0,8*np.pi,0.1)
r = 1
x = theta*np.cos(theta)
y = theta*np.sin(theta)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_len = np.linspace(0, r.max(), 200)
x_len = np.interp(r_int, r, x)
y_len = np.interp(r_int, r, y)
print(r_len)
print(x_len)
print(y_len)

[  0.           1.59335313   3.18670626   4.78005939   6.37341252
   7.96676565   9.56011879  11.15347192  12.74682505  14.34017818
  15.93353131  17.52688444  19.12023757  20.7135907   22.30694383
  23.90029696  25.4936501   27.08700323  28.68035636  30.27370949
  31.86706262  33.46041575  35.05376888  36.64712201  38.24047514
  39.83382827  41.4271814   43.02053454  44.61388767  46.2072408
  47.80059393  49.39394706  50.98730019  52.58065332  54.17400645
  55.76735958  57.36071271  58.95406585  60.54741898  62.14077211
  63.73412524  65.32747837  66.9208315   68.51418463  70.10753776
  71.70089089  73.29424402  74.88759715  76.48095029  78.07430342
  79.66765655  81.26100968  82.85436281  84.44771594  86.04106907
  87.6344222   89.22777533  90.82112846  92.4144816   94.00783473
  95.60118786  97.19454099  98.78789412 100.38124725 101.97460038
 103.56795351 105.16130664 106.75465977 108.34801291 109.94136604
 111.53471917 113.1280723  114.72142543 116.31477856 117.90813169
 119.501484

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [54]:
X = np.array([[3.0, 2.0, 1.0, 0.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
res = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
res &= (X.sum(axis=-1) == n)
print(X[res])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [61]:
X = np.random.randn(50)
N = 500
net = np.random.randint(0, X.size, (N, X.size))
means = X[net].mean(axis=1)
conf = np.percentile(means, [5, 95])
print(conf)

[-0.33247218  0.26821249]
